### ISSUE TITLE
SEO and Pubbing

### ISSUE THREAD

**Issue by mfpekala** [mfpekala/play-jpeg#7]
## Todos
- [ ] Basic research in to SEO and how to improve
- [ ] Write a Medium article on it
- [ ] Pub on HN, reddit, etc
